---
title: "Models-SI"
author: "Jeff Wesner"
output:
  bookdown::word_document2:
    toc: false
    number_sections: false
editor_options:
  markdown:
    wrap: 72
---

## Modelling

*Biomass flux of aquatic insects*

The goal for biomass modelling was to generate predictions of annual
insect emergence dry mass from rivers in each of 1,034,083 HydroBasins.
Annual global emergence was then estimated by summing emergence across
HydroBasins. To do this, we first converted literature-derived measures
of annual benthic macroinvertebrate secondary production ($P_b$) to
annual insect emergence production ($E_i$) in units of
$\text{mg} \cdot \text{DM} \cdot \text{m}^{-2} \cdot \text{y}^{-1}$. We
then estimated the non-linear relationships of $E_i$ with environmental
predictors and used the parameters from those models to predict
$E_{i,basin}$ in each HydroBasin based on the environmental conditions
of that basin. Finally, we multiplied the predicted $E_{i,basin}$ by the
amount of river water in each HydroBasin to yield the total emergence
production per basin. Finally, summing across all basins
$\sum_{basin=1}^{1,034,083} E_{i, basin}$ yielded the total annual
emergence biomass globally in units of kilograms or metric tons per
year. Below we describe each of these steps in sequence. To the extent
possible, we have followed the notation of Gratton and Vander Zanden
(2009).

*Annual Insect Emergence Production*

To convert benthic secondary production to insect emergence, we first
calculated the raw fraction of community production composed of insects
$(f_i)$ from the 113 studies that reported both community-level and
insect-only production. To estimate uncertainty in those proportions, we
fit an intercept only model with $f_i$ as the response variable as
follows:

$$f_i \sim \mathrm{Beta}(\mu, \phi)$$
$$\mathrm{logit}(\mu_{f_i}) \sim \mathrm{Normal}(0.66, 0.07)$$
$$\phi \sim \mathrm{Gamma}(0.01, 0.01)$$

The likelihood was Beta and the prior for the intercept was the
$N(0.66, 0.07)$, corresponding to a prior mean fraction of \~66%,
consistent with prior estimates by Gratton et al. (2009). This produced
a posterior distribution of the average fraction of secondary production
that are insects $\mu$. We took 1000 *k* draws from that distribution
and multiplied each draw by a corresponding benthic secondary production
estimate $P_b$ to yield a distribution of insect-only benthic secondary
production $P_{i}^k$, such that $P_{i}^k = P_b\cdot \mu^k$. Averaging
over the $k$ draws yielded a mean value of aquatic insect benthic
production $P_{i}$ for each corresponding measure of total secondary
production.

To convert $P_{i}$ to emergence production $E_i$, we first estimated the
posterior distribution of emergence-to-production ratios E:P using data
from Gratton et al. (2009) and Raitif et al. (2018). We used a Beta
likelihood and an intercept only model with varying intercepts for study
and taxon:

$$\text{E:P} \sim \mathrm{Beta}(\mu, \phi)$$
$$\mathrm{logit}(\mu_{E:P})  = \alpha + \alpha_{study} + \alpha_{taxon}$$
$$\alpha \sim \mathrm{Normal}(0.19, 0.05)$$
$$\alpha_{study} \sim \mathrm{Normal}(0, \sigma_{study}) $$
$$\alpha_{taxon} \sim \mathrm{Normal}(0, \sigma_{taxon}) $$
$$\sigma_{study},\sigma_{taxon} \sim \mathrm{Exponential}(2) $$
$$\phi \sim \mathrm{Gamma}(0.01, 0.01)$$

After obtaining this estimate, we Monte Carlo multiplied 1000 $k$ draws
from the posterior distribution of E:P ratios by 1000 $k$ draws from the
posterior distribution of insect production estimates
$E_i^k = \mu_{E:P}^k \cdot \mu_{f_i}^k$. Averaging over the draws
yielded 293 modeled estimates of median $E_i$. We combined these with 18
empirical estimates resulting in 311 total estimates of annual insect
emergence production $E_i$
($\text{mg} \cdot \text{DM} \cdot \text{m}^{-2} \cdot \text{y}^{-1}$).

*Relationships of emergence and environmental variables*

To determine which environmental variables best predicted emergence
$E_i$, we used generalized additive models (GAM) with median emergence
estimates from the above procedures (n = 311) as the response variable
and a set of environmental variables as predictors (Supplementary Table
Predictors). The likelihood was Gamma with a log-link. Prior values were
determined with prior predictive simulation (Wesner and Pomeranz 2021).
We fit 15 models (Supplementary Table Models) with predictors including
combinations of mean annual water temperature, mean annual
precipitation, and 8 other geospatial predictors. All models had varying
intercepts of author and HydroBasin, both of which were included to
allow posterior prediction to new locations. Values for the fixed
predictors were determined using the lat/lon location of each emergence
sample and the corresponding environmental variables available through
HydroAtlas (level 12). The general model structure was:

$$\frac{E_i}{\mathrm{max}(E_i)} \sim \mathrm{Gamma}(\mu, \phi)$$

$$\mathrm{log}(\mu) = \alpha + f(\textbf{X}) + \alpha_{study} + \alpha_{basin} $$

$$ \alpha \sim \mathrm{Normal}(-5, 2) $$

$$
f(\textbf{X}) = \sum_{k = 1}^K \beta_kb_k(\textbf{X})$$

$$
\beta_k \sim \mathrm{Normal}(0, \sigma_{f})
$$

$$
b_k \sim \mathrm{Normal}(0, 2)
$$

$$ \sigma_f \sim \mathrm{Student T}(3, 0, 2.5) $$

$$\alpha_{study} \sim \mathrm{Normal}(0, \sigma_{study})$$

$$\alpha_{basin} \sim \mathrm{Normal}(0, \sigma_{basin})$$

$$\sigma_{study}, \sigma_{basin} \sim \mathrm{Exponential}(4)$$

$$\phi \sim \mathrm{Exponential}(0.01),$$

where the response variable $E_i$ is annual insect emergence production.
To improve model fit and simplify the prior selection, $E_i$ was
standardized to the 0-1 scale by dividing each value by the maximum
$E_i$ prior to fitting. The likelihood is Gamma with an unknown mean
$\mu$ and shape $\phi$. The mean $\mu$ is described by an intercept
$\alpha$ and varying intercepts for study $\alpha_{study}$ and
HydroBasin $\alpha_{basin}$, along with the thin-plate spline smoothing
function $f(\textbf{X})$ for $\textbf{X}$ predictors. The smoothing
function is described by $k$ basis functions $b_k$ and their
corresponding weights $\beta_k$. The total $k$ varies by model as
determined using the algorithms in `mgcv` (Wood 2025). The remaining
lines denote prior distributions for each parameter
($\alpha, \beta_k, b_k\,\alpha_{study}, \alpha_{basin}, \phi$) and
hyperparameter ($\sigma_f, \sigma_{study}, \sigma_{basin}$).

*Model comparison and global predictions*

We compared the 15 models using leave-one-out-cross-validation (Vehtari
et al. 2017) with the *loo()* function in `brms` (Bürkner 2017). Four of
the top five models all had mean annual water temperature and/or mean
annual precipitation in univariate, additive, or interactive forms. The
remaining model was an intercept only model with no fixed predictors.
For this reason, we used the model with main effects and interactions of
mean annual water temperature and mean annual precipitation to predict
$E_i$ in each of the 1,034,083 HydroBasins in units of
$\text{kg} \cdot \text{DM} \cdot \text{m}^{-2} \cdot \text{y}^{-1}$.
Multiplying this by the area of river water in each HydroBasin yielded
the total flux per basin ($E_{i, basin}$;
$\text{kg} \cdot \text{DM} \cdot \text{basin}^{-1} \cdot \text{y}^{-1}$).
We did this across 1000 $k$ draws of the posterior distribution. Summing
over basins for each draw yielded a posterior distribution of global
insect emergence $E_{i, global}$ in units of
$\text{metric tons} \cdot \text{DM} \cdot \text{y}^{-1}$.

*Range of data in the training data versus global data*

Across the samples with emergence estimates, mean annual stream
temperature ranged from 1 to 25°C (**Extended data** **Table SX**). That
covered \~96% of the global range of temperatures across all 1,034,083
HydroBasins. Mean annual precipitation in the emergence estimates
covered a smaller percentage (\~40%) of the global range. However, the
median and 95% confidence intervals for precipitation (and temperature)
had strong overlap with similar bounds (177 to 2792 mm/m²/y for the raw
data vs 15 to 2791 across the HydroBasins) (**Extended data Table SX**).

*Nutrient flux in adult aquatic insects*

In addition to dry mass, we estimated fluxes of carbon, nitrogen,
phosphorous, and polyunsaturated fatty acids (PUFAs) by converting dry
mass based on conversion ratios. For carbon, we first converted dry mass
(DM) to ash-free dry mass (AFDM): $\text{AFDM} = 0.9\times\text{DM}$
(Benke et al. 1999). Carbon (C) was then estimated as
$\text{C} = 0.5\times\text{AFDM}$ (Waters 1977). Nitrogen (N) and
phosphorous (P) were estimated using stoichiometric ratios of 6.3 C:N
and 124 C:P (Elser et al. 2000).

No standard conversions exist for PUFA. Therefore, we conducted
literature searches in ISI Web of Science using search terms including
“PUFA*”, Poly-unsaturated fatty acid*”, “aquatic insect\*”, and
“emergence” to identify articles on the PUFA content of adult aquatic
insects. We focused on the years 2019 to 2024, with information before
2019 taken from recent review papers (Gladyshev et al. 2019; Moyo 2020).
We identified those articles that reported quantitative PUFA
concentrations per unit of biomass of emerging insects. Additional
relevant papers were found examining references within the papers
directly. We estimated fluxes of long-chain poly-unsaturated fatty acids
(LC-PUFA) by first extracting 32 records of LC-PUFA concentrations from
the literature. Of these 32 records, we limited our analysis to 25 that
reported sum concentrations of the docosahexaenoic acid (DHA) and
eicosatetraenoic acid (EPA) in adult aquatic insects. One record was
reported as DHA + EPA in “adult aquatic insects”, but all other were
reported as DHA + EPA in individual insect Orders, including Diptera
(e.g., Chironomidae, Culicidae), Ephemeroptera, Odonata, Trichoptera,
and Plecoptera. We used these data to estimate the average concentration
of EPA + DHA in adult aquatic insects using the following model:

$$\mathrm{F}_s \sim \mathrm{Gamma}(\mu, \phi)$$

$$\mathrm{log}(\mu) = \alpha +  \alpha_{study} +  \alpha_{taxon}$$

$$ \alpha \sim \mathrm{Normal}(-3, 1) $$

$$
\alpha_{study} \sim \mathrm{Normal}(0, \sigma_{study})$$

$$
\alpha_{taxon} \sim \mathrm{Normal}(0, \sigma_{taxon})$$

$$ \sigma_{study},\sigma_{taxon} \sim \mathrm{Exponential}(2) $$

$$ \phi \sim \mathrm{Gamma}(0.01, 0.01), $$

where $\mathrm{F}_s$ is the standardized adult tissue concentration of
DHA + EPA (standardized by dividing by the maximum concentration), with
varying intercepts for study $\alpha_{study}$ and taxon $\alpha_{taxon}$
. Because tissue concentrations are positive and continuous, we used a
gamma likelihood with a log-link. Given the standardized data and
log-link, we used a N(-3, 1) prior for the intercept and N(0, 1) prior
for the slope, with an exponential(2) prior for the hyperparameter
$\sigma_{study}$ and Gamma(0.01, 0.01) for $\phi$.

After un-standardizing, this yielded a posterior distribution of PUFA
concentrations in units of $\mathrm{ng}\cdot\mathrm{mgDM}^{-1}$. To
convert this to annual flux, we multiplied each estimate of dry mass
flux by $k = 100$ draws of PUFA, then took the median of across the 100
draws, yielding estimates of PUFA flux in units of $\mathrm{mg}$ or
$\mathrm{kg}\cdot\mathrm{y}^{-1}$ .

*Contaminant flux in adult aquatic insects*

The goal for contaminant modelling was to convert dry mass estimates
from biomass modelling into tissue concentrations of metalloids,
herbicides, fungicides, and pesticides. To do this, we extracted X
studies from the literature that reported water concentrations and adult
tissue concentrations of a contaminant. We then modeled this
relationship using generalized linear mixed models, yielding predictions
of adult tissue concentrations $C_a$ in units of
$\mathrm{ng}\cdot\mathrm{mgDM}^{-1}$ as a continuous function of water
concentrations $C_w$. To scale this globally, we generated posterior
predictions of $C_a$ in each of the 1,034,083 HydroBasin using the mean
$C_w$ in each HydroBasin derived from **JAKOB'S METHOD**. This generated
basin level predictions of adult tissue concentrations of contaminants
$C_{a,basin}$. Multiplying these by estimates of adult aquatic insect
emergence $E_{i,basin}$ yielded predictions of contaminant flux in each
HydroBasin $C_{f,basin}$, which we report in units of $\mathrm{mg}$ or
$\mathrm{kg}\cdot\mathrm{y}^{-1}$ .

To estimate the relationship between water concentrations $C_w$ and
adult concentrations $C_a$ of metalloids, herbicides, fungicides, and
pesticides, we fit separate generalized linear mixed models for each
compound with the following structure:

$$\frac{C_a}{\mathrm{max}(C_a)} \sim \mathrm{Gamma}(\mu, \phi)$$

$$\mathrm{log}(\mu) = \alpha + \beta C_w + \alpha_{study}$$

$$ \alpha \sim \mathrm{Normal}(-3, 1) $$

$$
\beta \sim \mathrm{Normal}(0, 1)
$$

$$
\alpha_{study} \sim \mathrm{Normal}(0, \sigma_{study})$$

$$ \sigma_{study} \sim \mathrm{HalfStudentT}(3, 0, 2.6) $$

$$ \phi \sim \mathrm{Gamma}(0.01, 0.01), $$

where $C_a$ is the adult tissue concentration of a contaminant
(standardized by dividing by the maximum concentration), $C_w$ is the
water concentration of the contaminant (standardized as a z-score), with
varying intercepts for study. Because tissue concentrations are positive
and continuous, we used a gamma likelihood with a log-link. Given the
standardized data and log-link, we used a N(-3, 1) prior for the
intercept and N(0, 1) prior for the slope, with a default priors of
HalfStudentT(3, 0, 2.6) for the hyperparameter $\sigma_{study}$ and
Gamma(0.01, 0.01) for $\phi$.
