---
title: "Models-main text"
author: "Jeff Wesner"
date: "2025-07-25"
output:
  bookdown::word_document2:
    toc: false
    number_sections: false
editor_options:
  markdown:
    wrap: 72
---



## Modelling

Biomass

The goal for biomass modelling was to generate predictions of annual insect emergence dry mass from rivers in each of 1,034,083 HydroBasins. Annual global emergence was then estimated by summing emergence across HydroBasins. To do this, we first converted literature-derived measures of annual benthic macroinvertebrate secondary production ($P_b$) to annual insect emergence production ($E_i$) in units of $\text{mg} \cdot \text{DM} \cdot \text{m}^{-2} \cdot \text{y}^{-1}$. We then estimated the non-linear relationships of $E_i$ with environmental predictors and used the parameters from those models to predict $E_{i,basin}$ in each basin based on the environmental conditions of that basin. Finally, we multiplied the predicted $E_{i,basin}$ by the amount of river water in each basin to yield the total emergence production per basin. Finally, summing across all basins $\sum_{basin=1}^{1,034,083} E_{i, basin}$ yielded the total annual emergence biomass globally in units of kilograms or metric tons per year. Below we describe each of these steps in sequence. To the extent possible, we have followed the notation of Gratton and Vander Zanden (2009).

*Annual Insect Emergence Production*

To convert benthic secondary production to insect emergence, we first calculated the raw fraction of community production composed of insects $(f_i)$ from the 113 studies that reported both community-level and insect-only production. To estimate uncertainty in those proportions, we fit an intercept only model with $f_i$ as the response variable as follows:

$$f_i \sim \mathrm{Beta}(\mu, \phi)$$ 
$$\mu_{f_i} \sim \mathrm{Normal}(0.66, 0.07)$$
$$\phi \sim \mathrm{Gamma}(0.01, 0.01)$$

The likelihood was Beta and the prior for the intercept was the $N(0.66, 0.07)$, corresponding to a prior mean fraction of \~66%, consistent with prior estimates by Gratton et al. (2009). This produced a posterior distribution of the average fraction of secondary production that are insects $\mu$. We took 1000 *k* draws from that distribution and multiplied each draw by a corresponding benthic secondary production estimate $P_b$ to yield a distribution of insect-only benthic secondary production $P_{i}^k$, such that $P_{i}^k = P_b\cdot \mu^k$. Averaging over the $k$ draws yielded a mean value of aquatic insect benthic production $P_{i}$ for each corresponding measure of total secondary production.

To convert $P_{i}$ to emergence production $E_i$, we first estimated the posterior distribution of emergence-to-production ratios E:P using data from Gratton et al. (2009) and Raitif et al. (2018). We used a Beta likelihood and an intercept only model with varying intercepts for study and taxon:

$$\text{E:P} \sim \mathrm{Beta}(\mu, \phi)$$
$$\mu_{E:P}  = \alpha + \alpha_{study} + \alpha_{taxon}$$
$$\alpha \sim \mathrm{Normal}(0.19, 0.05)$$
$$\alpha_{study} \sim \mathrm{Normal}(0, \sigma_{study} $$
$$\alpha_{taxon} \sim \mathrm{Normal}(0, \sigma_{taxon} $$
$$\sigma_{study},\sigma_{taxon} \sim \mathrm{Exponential}(2) $$
$$\phi \sim \mathrm{Gamma}(0.01, 0.01)$$


After obtaining this estimate, we Monte Carlo multiplied 1000 $k$ draws from the posterior distribution of E:P ratios by 1000 $k$ draws from the posterior distribution of insect production estimates $E_i^k = \mu_{E:P}^k \cdot \mu_{f_i}^k$. Averaging over the draws yielded 293 modeled estimates of median $E_i$. We combined these with 18 empirical estimates resulting in 311 total estimates of annual insect emergence production $E_i$ ($\text{mg} \cdot \text{DM} \cdot \text{m}^{-2} \cdot \text{y}^{-1}$).

*Relationships of emergence and environmental variables*

To determine which environmental variables best predicted emergence $E_i$, we used generalized additive models (GAM) with median emergence estimates from the above procedures (n = 311) as the response variable and a set of environmental variables as predictors (Supplementary Table Predictors). The likelihood was Gamma with a log-link. Prior values were determined with prior predictive simulation (Wesner and Pomeranz 2021). We fit 15 models (Supplementary Table Models) with predictors including combinations of mean annual water temperature, mean annual precipitation, and 8 other geospatial predictors. All models had varying intercepts of author and HydroBasin, both of which were included to allow posterior prediction to new locations. Values for the fixed predictors were determined using the lat/lon location of each emergence sample and the corresponding environmental variables available through HydroAtlas (level 12).

*Model comparison and global predictions*

We compared the 15 models using leave-one-out-cross-validation (Vehtari et al. 2017) with the *loo()* function in `brms` (Bürkner 2017). Four of the top five models all had mean annual water temperature and/or mean annual precipitation in univariate, additive, or interactive forms. The remaining model was an intercept only model with no fixed predictors. For this reason, we used the model with main effects and interactions of mean annual water temperature and mean annual precipitation to predict $E_i$ in each of the 1,034,083 HydroBasins in units of $\text{kg} \cdot \text{DM} \cdot \text{m}^{-2} \cdot \text{y}^{-1}$. Multiplying this by the area of river water in each HydroBasin yielded the total flux per basin ($E_{i, basin}$; $\text{kg} \cdot \text{DM} \cdot \text{basin}^{-1} \cdot \text{y}^{-1}$). We did this across 1000 $k$ draws of the posterior distribution. Summing over basins for each draw yielded a posterior distribution of global insect emergence $E_{i, global}$ in units of $\text{metric tons} \cdot \text{DM} \cdot \text{y}^{-1}$.
